### ISSUE TITLE
Remove Subscription Check isn't working

### ISSUE THREAD

**Issue by trickert76** [lae/ansible-role-proxmox#97]
I'm using the develop branch:

```
- src: https://github.com/lae/ansible-role-proxmox.git
  version: develop
  name: lae.proxmox
```

and make a `ansible-galaxy install --force -r roles/requirements.yml` and I'm still getting the message at `TASK [lae.proxmox : Remove subscription check wrapper function in web UI]`

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_patch_payload_e9ypt3al/ansible_patch_payload.zip/ansible/modules/files/patch.py", line 208, in main
  File "/tmp/ansible_patch_payload_e9ypt3al/ansible_patch_payload.zip/ansible/modules/files/patch.py", line 158, in apply_patch
PatchError: 1 out of 1 hunk FAILED
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored

fatal: [saturn]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": true,
            "basedir": "/",
            "binary": false,
            "dest": null,
            "remote_src": false,
            "src": "/root/.ansible/tmp/ansible-tmp-1596549500.348261-10773-167626737788042/00_remove_checked_command_buster.patch",
            "state": "present",
            "strip": 1
        }
    },
    "msg": "1 out of 1 hunk FAILED\nReversed (or previously applied) patch detected!  Skipping patch.\n3 out of 3 hunks ignored\n"
}
```

It is a Proxmox 6.2-10

**Comment by trickert76** [comment]
It looks like the both files are much bigger now and the offsets are wrong:

```
--- proxmoxlib.js.original	2020-08-04 16:49:33.000000000 +0200
+++ proxmoxlib.js	2020-08-04 16:47:24.000000000 +0200
@@ -7446,7 +7446,7 @@
 	let update_btn = new Ext.Button({
 	    text: gettext('Refresh'),
 	    handler: function() {
-		Proxmox.Utils.checked_command(function() { apt_command('update'); });
+		apt_command('update');
 	    },
 	});
```


and

```
--- pvemanagerlib.js.original	2020-08-04 16:50:13.000000000 +0200
+++ pvemanagerlib.js	2020-08-04 16:47:39.000000000 +0200
@@ -3151,7 +3151,6 @@
 		handler: function(data) {
 		    me.login = null;
 		    me.updateLoginData(data);
-		    Proxmox.Utils.checked_command(function() {}); // display subscription status
 		}
 	    });
 	}
@@ -28330,7 +28329,7 @@
 		{
 		    text: gettext('System Report'),
 		    handler: function() {
-			Proxmox.Utils.checked_command(function() { me.showReport(); });
+			me.showReport();
 		    },
 		},
 	    ],
@@ -28428,7 +28427,7 @@
 	var version_btn = new Ext.Button({
 	    text: gettext('Package versions'),
 	    handler: function(){
-		Proxmox.Utils.checked_command(function() { me.showVersions(); });
+		me.showVersions();
 	    }
 	});

```

**Comment by trickert76** [comment]
But I'm not sure if this a 6.2x Issue or also in 6.1 and how can we determine that?

**Comment by lae** [comment]
Sorry, I had actually fixed this locally last week when updating my homelab but forgot to commit/push it. See 7f547dd6029e947c82b3e564c7751bb9831bd30c.

This is a 6.2x issue, but we don't discern much between minor versions in this role since there's an expectation that if you're updating the role, you're also keeping your Proxmox installation up to date.
